
'use server';
/**
 * @fileOverview An AI flow for generating high-quality, helpful articles based on strict guidelines.
 *
 * - generateArticle - A function that handles the article and image generation process.
 * - GenerateArticleInput - The input type for the generateArticle function.
 * - GenerateArticleOutput - The return type for the generateArticle function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'zod';

const GenerateArticleInputSchema = z.object({
  topic: z.string().describe('The topic of the article to generate.'),
  category: z.string().describe('The category of the article (e.g., Engine, Sensors).')
});
export type GenerateArticleInput = z.infer<typeof GenerateArticleInputSchema>;

const GenerateArticleOutputSchema = z.object({
  title: z
    .string()
    .describe('A helpful, user-friendly title for the article. It should be clear and accurately reflect the content.'),
  summary: z
    .string()
    .describe('A detailed and helpful summary of the article, approximately 25-35 words long. It should capture the main points and entice the user to read more.'),
  content: z
    .string()
    .describe(
      'The full, detailed, and helpful article content, in Markdown format. It must be at least 500 words and well-structured.'
    ),
  imageUrl: z.string().url().describe("A URL for a hero image for the article, generated by an AI model. The image should be visually appealing and directly related to the article's topic.")
});
export type GenerateArticleOutput = z.infer<typeof GenerateArticleOutputSchema>;


const articlePrompt = ai.definePrompt({
  name: 'articleGeneratorPrompt',
  model: 'googleai/gemini-1.5-flash',
  input: {schema: z.object({ topic: z.string() })},
  output: {schema: z.object({
      title: GenerateArticleOutputSchema.shape.title,
      summary: GenerateArticleOutputSchema.shape.summary,
      content: GenerateArticleOutputSchema.shape.content
  })},
  prompt: `
You are an expert automotive writer with a "human-first, help-first" philosophy. Your goal is to create genuinely useful and original content that solves real user problems, without any AI fluff, keyword stuffing, or robotic patterns.

You must generate an article on the topic: '{{{topic}}}'.

The article MUST adhere to the following strict standards:
1.  **Title:** The title should be helpful and user-friendly.
2.  **Summary:** The summary MUST be detailed and helpful, approximately 25-35 words long.
3.  **Word Count:** The body of the article MUST be at least 500 words long.
4.  **Tone:** The writing style must be natural, empathetic, and engaging, as if written by a seasoned, helpful human expert.
5.  **Structure & Formatting:** The response MUST be in well-structured Markdown format.
    - The content MUST begin with an H1 heading (e.g., "# Title"). This is critical.
    - Use subheadings (H2, H3, etc.) to organize the information clearly.
    - Include bullet points and tables where appropriate to make complex information easy to digest.
`,
  config: {
    safetySettings: [
      {
        category: 'HARM_CATEGORY_DANGEROUS_CONTENT',
        threshold: 'BLOCK_NONE',
      },
       {
        category: 'HARM_CATEGORY_HATE_SPEECH',
        threshold: 'BLOCK_NONE',
      },
      {
        category: 'HARM_CATEGORY_HARASSMENT',
        threshold: 'BLOCK_NONE',
      },
      {
        category: 'HARM_CATEGORY_SEXUALLY_EXPLICIT',
        threshold: 'BLOCK_NONE',
      }
    ]
  }
});


export const generateArticleFlow = ai.defineFlow(
  {
    name: 'generateArticleFlow',
    inputSchema: GenerateArticleInputSchema,
    outputSchema: GenerateArticleOutputSchema,
  },
  async (input) => {
    const imagePrompt = `A photorealistic, high-resolution hero image for a technical automotive blog post with global appeal about "${input.topic}". The image should be clean, professional, and not specific to any single country. Use cinematic lighting and a strong, universally recognizable visual element. Avoid text or clutter.`;

    // Generate the article text and the image in parallel to save time.
    const [articleResponse, imageResponse] = await Promise.all([
        articlePrompt({ topic: input.topic }),
        ai.generate({
            model: 'googleai/gemini-2.0-flash-preview-image-generation',
            prompt: imagePrompt,
            config: {
                responseModalities: ['TEXT', 'IMAGE'],
            },
        }).catch(err => {
            console.warn('Gemini image generation failed:', err);
            // On failure, create a placeholder URL using Pollinations AI
            const fallbackPrompt = `A photorealistic, high-resolution hero image for a technical automotive blog post with global appeal about "${input.topic}".`;
            const fallbackUrl = `https://image.pollinations.ai/prompt/${encodeURIComponent(fallbackPrompt)}?width=600&height=400&nologo=true`;
            return { media: { url: fallbackUrl } }; // Mimic the successful response structure
        })
    ]);

    const articleOutput = articleResponse.output;
    
    if (!articleOutput) {
      throw new Error('Failed to generate article content.');
    }
    
    // Ensure we have a URL, either from Gemini or the fallback.
    const imageUrl = imageResponse?.media?.url;
    if (!imageUrl) {
        throw new Error('Image generation failed and fallback also failed.');
    }


    return {
        title: articleOutput.title,
        summary: articleOutput.summary,
        content: articleOutput.content,
        imageUrl: imageUrl,
    };
  }
);


export async function generateArticle(
  input: GenerateArticleInput
): Promise<GenerateArticleOutput> {
  const result = await generateArticleFlow(input);
  
  // The model might ignore the prompt and put the H1 title inside the content.
  // This is a safeguard to ensure it's not duplicated.
  let processedContent = result.content.trim();
  const titleAsH1WithSpace = `# ${result.title}`;
  const titleAsH1NoSpace = `#${result.title}`;
  
  // Check for the title as an H1, with or without a space, case-insensitively.
  if (processedContent.toLowerCase().startsWith(titleAsH1WithSpace.toLowerCase())) {
      processedContent = processedContent.substring(titleAsH1WithSpace.length).trim();
  } else if (processedContent.toLowerCase().startsWith(titleAsH1NoSpace.toLowerCase())) {
      processedContent = processedContent.substring(titleAsH1NoSpace.length).trim();
  } else if (processedContent.toLowerCase().startsWith(result.title.toLowerCase())) {
      // Also check for the title without any markdown heading
      processedContent = processedContent.substring(result.title.length).trim();
  }

  return {
    ...result,
    content: processedContent,
  };
}
