
'use server';
/**
 * @fileOverview An AI flow for generating high-quality, helpful articles based on strict guidelines.
 *
 * - generateArticle - A function that handles the article and image generation process.
 * - GenerateArticleInput - The input type for the generateArticle function.
 * - GenerateArticleOutput - The return type for the generateArticle function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'zod';

const GenerateArticleInputSchema = z.object({
  topic: z.string().describe('The topic of the article to generate.'),
  category: z.string().describe('The category of the article (e.g., Engine, Sensors).')
});
export type GenerateArticleInput = z.infer<typeof GenerateArticleInputSchema>;

const GenerateArticleOutputSchema = z.object({
  title: z
    .string()
    .describe('The title of the article. It must be exactly 9 words long.'),
  summary: z
    .string()
    .describe('A short, SEO-friendly summary of the article (around 160 characters).'),
  content: z
    .string()
    .describe(
      'The full, detailed, and helpful article content, in Markdown format. It must be at least 1500 words and include a "6 Key Takeaways" section at the end.'
    ),
  imageUrl: z.string().url().describe("A URL for a hero image for the article, generated by an AI model. The image should be visually appealing and directly related to the article's topic.")
});
export type GenerateArticleOutput = z.infer<typeof GenerateArticleOutputSchema>;


const articlePrompt = ai.definePrompt({
  name: 'articleGeneratorPrompt',
  input: {schema: z.object({ topic: z.string() })},
  output: {schema: z.object({
      title: GenerateArticleOutputSchema.shape.title,
      summary: GenerateArticleOutputSchema.shape.summary,
      content: GenerateArticleOutputSchema.shape.content
  })},
  prompt: `You are an expert automotive writer with a "human-first, help-first" philosophy. Your goal is to create genuinely useful and original content that solves real user problems, without any AI fluff, keyword stuffing, or robotic patterns.

You must generate an article on the topic: '{{{topic}}}'.

The article MUST adhere to the following strict standards:
1.  **Title:** The title MUST be exactly 9 words long. It should be clear, user-friendly, and focused on the topic.
2.  **Word Count:** The body of the article MUST be exactly 1500 words long.
3.  **Tone:** The writing style must be natural, empathetic, and engaging, as if written by a seasoned, helpful human expert.
4.  **Structure:** The response MUST be in well-structured Markdown format. It must follow this exact order:
    -   Introduction: Start with a relatable introduction that hooks the reader.
    -   Main Body: Provide helpful, accurate, and in-depth content. Use subheadings (H2, H3, etc.) as needed to organize the information clearly.
    -   Final Summary: Conclude with a concise summary of the article's main points.
    -   **MANDATORY: 6 Key Takeaways:** At the very end of the content, you MUST include a section titled "## 6 Key Takeaways". This section MUST contain a bulleted list of exactly six of the most important, actionable points from the article. This is a non-negotiable requirement for every article.

**CRITICAL:** The 'content' field MUST NOT start with an H1 heading (e.g., "# Title"). The article's title is handled by the separate 'title' field. The content should begin directly with the first paragraph of the introduction.

Your final output must contain the generated title, a concise SEO-friendly summary (around 160 characters), and the full 1500-word article content in Markdown. The content MUST conclude with the "## 6 Key Takeaways" section as described above.
`,
});


export const generateArticleFlow = ai.defineFlow(
  {
    name: 'generateArticleFlow',
    inputSchema: GenerateArticleInputSchema,
    outputSchema: GenerateArticleOutputSchema,
  },
  async (input) => {
    const imagePrompt = `A photorealistic, high-resolution hero image for a technical automotive blog post with global appeal about "${input.topic}". The image should be clean, professional, and not specific to any single country. Use cinematic lighting and a strong, universally recognizable visual element. Avoid text or clutter.`;

    // Generate the article text and the image in parallel to save time.
    const [articleResponse, imageResponse] = await Promise.all([
        articlePrompt({ topic: input.topic }),
        ai.generate({
            model: 'googleai/gemini-2.0-flash-preview-image-generation',
            prompt: imagePrompt,
            config: {
                responseModalities: ['TEXT', 'IMAGE'],
            },
        }).catch(err => {
            console.warn('Gemini image generation failed:', err);
            return null; // Return null on error to handle fallback
        })
    ]);

    const articleOutput = articleResponse.output;
    
    if (!articleOutput) {
      throw new Error('Failed to generate article content.');
    }

    let imageUrl;
    if (imageResponse?.media?.url) {
        imageUrl = imageResponse.media.url;
    } else {
        console.warn('Gemini image generation failed, falling back to Pollinations AI.');
        const fallbackPrompt = `A photorealistic, high-resolution hero image for a technical automotive blog post with global appeal about "${input.topic}".`;
        imageUrl = `https://image.pollinations.ai/prompt/${encodeURIComponent(fallbackPrompt)}?width=600&height=400&nologo=true`;
    }

    return {
        title: articleOutput.title,
        summary: articleOutput.summary,
        content: articleOutput.content,
        imageUrl: imageUrl,
    };
  }
);


export async function generateArticle(
  input: GenerateArticleInput
): Promise<GenerateArticleOutput> {
  const result = await generateArticleFlow(input);
  
  // The model might ignore the prompt and put the H1 title inside the content.
  // This is a safeguard to ensure it's not duplicated.
  let processedContent = result.content.trim();
  const titleAsH1 = `# ${result.title}`;
  
  if (processedContent.startsWith(titleAsH1)) {
      processedContent = processedContent.substring(titleAsH1.length).trim();
  } else if (processedContent.startsWith(result.title)) {
      processedContent = processedContent.substring(result.title.length).trim();
  }

  return {
    ...result,
    content: processedContent,
  };
}
