
import Link from "next/link";
import type { Metadata } from "next";
import { Suspense } from "react";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { ArticleGrid } from "@/components/article-grid";
import { categoryDetails } from "@/lib/definitions";
import { CategoryCard } from "@/components/category-card";
import {
  Users,
  BookOpen,
  BrainCircuit,
  Wrench,
  Star,
} from "lucide-react";
import { getRecentArticles } from "@/lib/data";
import { ArticleGridSkeleton } from "@/components/article-grid-skeleton";


export const metadata: Metadata = {
  description: "A genuinely helpful automotive knowledge base. Get original, useful, and accurate articles on car repair, maintenance, and technology, all written with a human-first approach.",
  keywords: ["car repair help", "automotive maintenance guides", "vehicle help", "car problems", "DIY car repair", "Car Diagnostics BrainAi"],
};

const howItWorksSteps = [
  {
    icon: Users,
    title: "Start with a Question",
    description: "Think of a real-world car problem or a topic you're curious about.",
  },
  {
    icon: BookOpen,
    title: "Explore Our Library",
    description: "Browse categories or our full blog to find a helpful, in-depth article.",
  },
  {
    icon: BrainCircuit,
    title: "Gain Real Knowledge",
    description: "Our AI-powered, human-centric articles provide clear, actionable advice.",
  },
  {
    icon: Wrench,
    title: "Apply Your Learning",
    description: "Use your newfound knowledge for DIY tasks or informed talks with mechanics.",
  },
];

const testimonials = [
  {
    name: "Sarah J.",
    review: "Finally, a car website that actually helps! The articles are so detailed and easy to follow. I was able to fix a sensor issue myself.",
    rating: 5,
  },
  {
    name: "Mike T.",
    review: "As someone who knows nothing about cars, this site is a lifesaver. The 'Key Takeaways' section is brilliant for quick summaries.",
    rating: 5,
  },
  {
    name: "Carlos R.",
    review: "Incredibly well-written content without the usual fluff. This is now my go-to resource before I even think about visiting a mechanic.",
    rating: 5,
  },
];

const faqItems = [
    {
    question: "What is Car Diagnostics BrainAi?",
    answer: "Car Diagnostics BrainAi is an intelligent knowledge base dedicated to providing genuinely helpful, original, and accurate articles about automotive repair and maintenance. Our core philosophy is to help readers solve real-life problems.",
  },
  {
    question: "How is the content created?",
    answer: "Our content is generated by an advanced AI system that is guided by a 'human-first' principle. Every day, it automatically writes multiple new, in-depth articles on unique topics, which are then added to our permanent library.",
  },
  {
    question: "Are the articles accurate and reliable?",
    answer: "We strive for the highest accuracy. The AI is trained to produce useful, factual content. However, all articles are for informational purposes and should not replace advice from a qualified professional mechanic.",
  },
  {
    question: "Do I need any tools to use this website?",
    answer: "No, not at all. Our website is a free knowledge platform accessible on any device. No scanners, hardware, or special tools are required. Our goal is to empower you with information.",
  },
  {
    question: "How often is new content published?",
    answer: "Our automated system is constantly at work. We publish multiple new articles throughout the day, every day, to ensure our library is always growing with fresh, helpful content.",
  },
  {
    question: "Can I search for a specific topic?",
    answer: "Yes! You can use the search bar on the 'Blog' page to find articles related to specific keywords. You can also browse by category to explore different areas of automotive care."
  },
  {
    question: "Is Car Diagnostics BrainAi free to use?",
    answer: "Yes, access to all of our articles and diagnostic information is completely free. Our mission is to make automotive knowledge accessible to everyone."
  },
  {
    question: "How does the site make money if it's free?",
    answer: "We focus on building a large, engaged audience. The site is supported through unobtrusive advertising and affiliate partnerships for tools or parts we genuinely recommend. This allows us to keep the core content free."
  },
  {
    question: "Can I contribute articles or suggest topics?",
    answer: "Currently, all our content is AI-generated to maintain a consistent style and quality. However, we love hearing from our users! Please use our Contact page to suggest topics you'd like to see covered."
  },
  {
    question: "What is a cron job and how does it relate to this site?",
    answer: "A cron job is simply a scheduled task that runs automatically. We use a Vercel Cron Job to trigger our AI to write new articles at regular intervals (e.g., every hour). This ensures our content library is always fresh without any manual intervention."
  }
];


async function HomepageContent() {
  const trendingArticles = await getRecentArticles(6);
  return <ArticleGrid articles={trendingArticles} />;
}


export default function HomePage() {
  return (
    <div className="flex flex-col">
      {/* Hero Section */}
      <section className="bg-primary text-primary-foreground py-20 md:py-32">
        <div className="container mx-auto px-4 text-center">
          <div>
            <h1 className="text-4xl md:text-6xl font-extrabold tracking-tight mb-4">
              Genuinely Helpful Car Repair and Maintenance Guides
            </h1>
            <p className="text-lg md:text-xl text-primary-foreground/80 max-w-3xl mx-auto mb-8">
              Original, useful, and accurate help for real-life automotive problems. Written for humans, by an intelligent system focused on quality.
            </p>
            <Button size="lg" variant="secondary" asChild>
              <Link href="/blog">Explore Our Articles</Link>
            </Button>
          </div>
        </div>
      </section>

      {/* Trending Articles Section */}
      <section className="py-16 md:py-24 bg-background">
        <div className="container mx-auto px-4">
          <div>
            <h2 className="mb-8 text-center text-3xl font-extrabold tracking-tight text-primary lg:text-4xl">
              Recently Added Articles
            </h2>
            <p className="mx-auto -mt-4 max-w-2xl text-center text-lg text-muted-foreground">Our library grows every day with new, in-depth articles. Here are the latest additions.</p>
          </div>
           <Suspense fallback={<ArticleGridSkeleton count={6} />}>
            <HomepageContent />
          </Suspense>
        </div>
      </section>

      {/* How It Works Section */}
      <section className="py-16 md:py-24 bg-secondary/50">
        <div className="container mx-auto px-4">
          <div className="text-center mb-12">
            <h2 className="text-3xl md:text-4xl font-bold text-primary">Our Help-First Approach</h2>
            <p className="text-muted-foreground mt-2">A simple, 4-step process to empower you with knowledge.</p>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-4 gap-8">
            {howItWorksSteps.map((step) => (
              <div key={step.title} className="text-center flex flex-col items-center">
                <div className="bg-primary/10 text-primary rounded-full p-4 mb-4">
                  <step.icon className="h-8 w-8" />
                </div>
                <h3 className="text-lg font-semibold mb-2">{step.title}</h3>
                <p className="text-muted-foreground text-sm">{step.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>
      
      {/* Explore Categories Section */}
      <section className="py-16 md:py-24 bg-background">
        <div className="container mx-auto px-4">
          <div className="text-center mb-12">
            <h2 className="text-3xl md:text-4xl font-bold text-primary">Explore Automotive Categories</h2>
            <p className="text-muted-foreground mt-2">Find articles and advice on specific car systems and topics.</p>
          </div>
          <div className="grid grid-cols-1 gap-8 sm:grid-cols-2 lg:grid-cols-3">
            {categoryDetails.map((category) => (
              <CategoryCard key={category.name} category={category} />
            ))}
          </div>
        </div>
      </section>

      {/* Testimonials Section */}
      <section className="py-16 md:py-24 bg-primary text-primary-foreground">
        <div className="container mx-auto px-4">
          <div className="text-center mb-12">
            <h2 className="text-3xl md:text-4xl font-bold">What Our Readers Say</h2>
            <p className="text-primary-foreground/80 mt-2">Real feedback from people we've helped.</p>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {testimonials.map((testimonial) => (
              <Card key={testimonial.name} className="flex flex-col bg-background/10 border-primary-foreground/20 text-primary-foreground">
                <CardHeader>
                  <div className="flex items-center gap-1">
                    {Array.from({ length: testimonial.rating }).map((_, i) => (
                      <Star key={i} className="h-5 w-5 text-amber-400 fill-amber-400" />
                    ))}
                  </div>
                </CardHeader>
                <CardContent className="flex-grow">
                  <p className="mb-4">"{testimonial.review}"</p>
                  <p className="font-semibold text-primary-foreground/80">- {testimonial.name}</p>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* FAQ Section */}
      <section className="py-16 md:py-24 bg-secondary/50">
        <div className="container mx-auto px-4 max-w-3xl">
          <div className="text-center mb-12">
            <h2 className="text-3xl md:text-4xl font-bold text-primary">Frequently Asked Questions</h2>
          </div>
          <div>
            <Accordion type="single" collapsible className="w-full">
              {faqItems.map((item) => (
                <AccordionItem key={item.question} value={item.question}>
                  <AccordionTrigger>{item.question}</AccordionTrigger>
                  <AccordionContent>{item.answer}</AccordionContent>
                </AccordionItem>
              ))}
            </Accordion>
          </div>
        </div>
      </section>

      {/* Newsletter Signup Section */}
      <div className="bg-primary py-16 text-primary-foreground">
        <div className="container mx-auto px-4 text-center">
          <h2 className="text-3xl font-bold mb-2">Get Our Best Content Weekly</h2>
          <p className="text-primary-foreground/80 mb-6">Join our newsletter for helpful maintenance advice and new article alerts.</p>
          <form className="flex max-w-md mx-auto">
            <Input 
              type="email" 
              placeholder="Enter your email" 
              className="bg-card text-card-foreground rounded-r-none border-r-0"
              aria-label="Email for newsletter"
            />
            <Button type="submit" variant="secondary" className="rounded-l-none">
              Subscribe
            </Button>
          </form>
        </div>
      </div>
    </div>
  );
}
